#!/usr/bin/env python3

import sys
from math import *

a = 0
b = 5000
n = 10000
h = (b - a) / n
pi_2 = pi / 2

def my_function(x, fun):
    if x == 0:
        return 1
    p = 1
    for i in range(fun + 1):
        p = p * (sin(x / (2 * i + 1)) / (x / (2 * i + 1)))
    return (p)

def my_rect(fun):
    res = 0
    for i in range(n):
        res = res + my_function(a + i * h, fun)
    res = res * h
    print("I%d = %.10f" %(fun, res))
    if (res - pi_2 > -0.0000000001 and res - pi_2 < 0):
        print("diff = 0.0000000000\n")
    else:
        print("diff = %.10f\n" %(res - pi_2))

def my_trapez(fun):
    res = 0
    for i in range(1, n):
        res += my_function(a + i * h, fun)
    res = res * 2
    res = res + (my_function(a, fun) + my_function(b, fun))
    res = res * (h / 2)
    print("I%d = %.10f" %(fun, res))
    if (res - pi_2 > -0.0000000001 and res - pi_2 < 0):
        print("diff = 0.0000000000\n")
    else:
        print("diff = %.10f\n" %(res - pi_2))

def my_simpson(fun):
    res1 = 0
    res2 = 0
    for i in range(0, n):
        res1 += my_function(a + i * h + h / 2, fun)
    res1 = res1 * 4
    for i in range(1, n):
        res2 += my_function(a + i * h, fun)
    res2 = res2 * 2
    res = res1 + res2
    res = res + (my_function(a, fun) + my_function(b, fun))
    res = res * (h / 6)
    print("I%d = %.10f" %(fun, res))
    if (res - pi_2 > -0.0000000001 and res - pi_2 < 0):
        print("diff = 0.0000000000")
    else:
        print("diff = %.10f" %(res - pi_2))

def usage():
    print("USAGE:\n" "\t\t{} n\n" "DESCRIPTION\n" "\t\tn\tconstant defining the integral to be computed".format(sys.argv[0]))

def init_arg():
    try:
        arg = int(sys.argv[1])
    except ValueError:
        usage()
        exit(84)
    if (arg < 0):
        usage()
        exit(84)
    return (arg)

def check_args():
    if "--help" in sys.argv or "-h" in sys.argv:
        usage()
        sys.exit(0)
    if len(sys.argv) != 2:
        usage()
        sys.exit(84)

def main():
    check_args()
    arg = init_arg()
    func = 1
    print("Rectangles:")
    my_rect(arg)
    print("Trapezoids:")
    my_trapez(arg)
    print("Simpson:")
    my_simpson(arg)


if __name__ == '__main__':
    main()
